version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i8studio_app
    restart: unless-stopped
    environment:
      DATABASE_URL: file:/app/prisma/data/i8studio.db
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://i8studio.vn
      NODE_ENV: production
    volumes:
      - /opt/i8studio/data/db:/app/prisma/data
      - /opt/i8studio/data/uploads:/app/public/uploads
    networks:
      - techzen-net
    expose:
      - "3000"

networks:
  techzen-net:
    external: true
