server {
    listen 80;
    server_name demo.i8studio.vn;
    return 301 https://i8studio.vn$request_uri;
}
server {
    listen 443 ssl;
    server_name demo.i8studio.vn;
    ssl_certificate /home/cert/cert.pem;
    ssl_certificate_key /home/cert/private.key;
    return 301 https://i8studio.vn$request_uri;
}
